server:
  port: 8081

spring:
  application:
    name: commerce
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
