server:
  port: 8081

spring:
  application:
    name: commerce
  datasource:
    url: ${PG_DATASOURCE_URL}
    username: ${PG_DATASOURCE_USERNAME}
    password: ${PG_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Habilita a exibição de SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Formata as consultas SQL para melhor legibilidade
        use_sql_comments: true  # Inclui comentários nas consultas SQL

# custom fields
custom:
  MP_PUBLIC_KEY: ${MP_PUBLIC_KEY}
  MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
  MP_CLIENT_ID: ${MP_CLIENT_ID}
  MP_CLIENT_SECRET: ${MP_CLIENT_SECRET}
  SITE_BASEURL: "https://paibenedito.com.br"

logging:
  level:
    root: info
    org.springframework.boot.context.config: debug
    org.hibernate.SQL: debug  # Habilita o log das consultas SQL
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # Loga os parâmetros das consultas SQL
